### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by mycaravam** [asuh/sage-starter#4]
Anyone who wants to make this work with Bootstrap will have to make some changes. You will need to downgrade gulp-sass version to 2.3.2 and add the bootstrap scss code manually to main.scss. Maybe BS4.0 dropped bower support.

**Comment by asuh** [comment]
I know this was written a year ago and I did not get a notification that it was created but is this still an issue today? I haven't tested it since I purposely stripped out Bootstrap from this repo. If this is still an issue, I'll update the readme file with info about what's happening and why. Thanks!
